apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: loop4
  name: loop4
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - |-
      while true do; \
        do date;sleep 5; done
    image: busybox:1.36.1
    name: loop4
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
